services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./graphrag:/app/graphrag
      - ./graphrag_vertex:/app/graphrag_vertex
      - ./voc_test:/app/voc_test
      - ./voc_data:/app/voc_data
      - ./vertex_graphrag_test.py:/app/vertex_graphrag_test.py
      - ./secrets:/app/secrets
    working_dir: /app
    environment:
        - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/vertex-ai-client.json
    command: poetry run python
    tty: true
